
export const ADD_INGREDIENT = 'ADD_INGREDIENT';
export const DEL_INGREDIENT = 'DEL_INGREDIENT';

export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const PURCHASE_BURGER_SUCESS = 'PURCHASE_BURGER_SUCESS'
export const PURCHASE_BURGER_FAIL = 'PURCHASE_BURGER_FAIL';
export const PURCHASE_BURGER_START = 'PURCHASE_BURGER_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';

export const DOWLOAD_ORDERS_SUCESS = 'DOWLOAD_ORDERS_SUCESS';
export const DOWLOAD_ORDERS_FAIL = 'DOWLOAD_ORDERS_FAIL';
export const DOWLOAD_ORDERS_START = 'DOWLOAD_ORDERS_START';
export const DOWLOAD_ORDERS_INIT = 'DOWLOAD_ORDERS_INIT';

export const AUTH_START = 'AUTH_START';
export const AUTH_SUCESS = 'AUTH_SUCESS';
export const AUTH_FAIL = 'AUTH_FAIL';

